### ISSUE TITLE
请问有部署架构图吗

### ISSUE THREAD

**Issue by BinWu1989** [grpc-nebula/grpc-nebula#1]
请问是否可以提供一份部署架构图用于加深对系统架构的理解？

**Comment by shoppingsee** [comment]
https://github.com/grpc-nebula/grpc-nebula/blob/master/%E4%B8%9C%E6%96%B9%E8%AF%81%E5%88%B8%E5%BE%AE%E6%9C%8D%E5%8A%A1%E6%B2%BB%E7%90%86%E5%B9%B3%E5%8F%B0.md
